name: FAST GAZ ADMIN CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - deployment
      - main

jobs:
  build-and-push:
    name: Build and Push Web App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build --if-present

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/fast-gaz-admin:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/fast-gaz-admin:v1.0.0

  